spring.datasource.url=jdbc:mysql://localhost:3306/integrador3?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false