version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: integrador-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: Integrador
    ports:
      - "3306:3306"